# Generated by Django 2.2.7 on 2019-11-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='phone',
        ),
        migrations.AlterField(
            model_name='worker',
            name='nid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
