# Generated by Django 2.2.7 on 2019-11-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191118_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='Location',
            new_name='location',
        ),
        migrations.AddField(
            model_name='worker',
            name='type_of_work',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
