# Generated by Django 2.2.7 on 2019-11-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_worker_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
